version: '3.7'
services:
  postgres:
    image: postgres:10.4
    ports:
      - "5200:5432"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "db"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
